# Generated by Django 3.2.6 on 2021-08-20 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_admin', '0013_alter_team_team_code'),
        ('dre_jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Canceled', 'Canceled'), ('Complete', 'Complete')], default='Scheduled', max_length=50)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dre_jobs.customer')),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dre_admin.department')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dre_admin.team')),
            ],
        ),
    ]
