# Generated by Django 3.2.6 on 2021-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_jobs', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='RegisterDate',
            field=models.DateField(blank=True),
        ),
    ]
