# Generated by Django 3.2.6 on 2021-08-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_jobs', '0005_auto_20210820_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In-Progress', 'In-Progress'), ('On-Hold', 'On-Hold'), ('Canceled', 'Canceled'), ('Complete', 'Complete')], default='Scheduled', max_length=50),
        ),
    ]
