# Generated by Django 3.2.6 on 2021-08-17 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_code', models.CharField(default='All', max_length=20, unique=True)),
                ('dep_name', models.CharField(default='All', max_length=30)),
                ('dep_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_code', models.CharField(default='All', max_length=30, unique=True)),
                ('team_name', models.CharField(default='All', max_length=40)),
                ('team_description', models.TextField(null=True)),
                ('team_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dre_admin.department')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Department Head', 'Department Head'), ('Team Leader', 'Team Leader'), ('User', 'User')], default='User', max_length=50)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dre_admin.department')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dre_admin.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
