# Generated by Django 3.2.6 on 2021-08-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dre_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_dep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dre_admin.department'),
        ),
    ]
