# Generated by Django 3.2.6 on 2021-08-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dre_admin', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
