# Generated by Django 3.2.6 on 2021-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_admin', '0003_auto_20210818_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(default='All', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(default='All', max_length=30),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_code',
            field=models.CharField(default='All', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='All', max_length=40),
        ),
    ]
