# Generated by Django 3.2.6 on 2021-08-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_admin', '0007_auto_20210819_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(default='All', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dep_name',
            field=models.CharField(default='All', max_length=30, null=True),
        ),
    ]
