# Generated by Django 3.2.6 on 2021-08-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dre_admin', '0011_auto_20210819_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_code',
            field=models.CharField(default='All', max_length=20),
        ),
    ]
